### ISSUE TITLE
Updating different parts of after-work separately breaks it.

### ISSUE THREAD

**Issue by FredrikFolkesson** [qlik-oss/after-work.js#388]
Our CI tool bumped `@after-work.js/cli` and `@after-work.js/node` from 5.0.1 to 5.0.2 in two different PRs and then the tests would not run correctly. 

When bumped together it worked fine, but I would not expect a patch release to require another package to be updated to work

**Comment by stoffeastrom** [comment]
It's hard to tell without any more information. What did not run correctly?

**Comment by peol** [comment]
I believe he's referencing this build: https://circleci.com/gh/qlik-oss/mira/3629

**Comment by stoffeastrom** [comment]
Ouch, it wasn't meant to be breaking but I'm realising it was :/.

The idea was to support a scenario where you only need the `node` runner but looking at it we missed to actually ensure compatibility by having a separate package e.g  `cli-node` with dependencies to the `cli` and `node` packages. I think it make sense for the `node` runner but not for others. Either you use `@after-work.js/aw` or the to be `@after-work.js/cli-node`. This needs to be addressed and would indeed be a major bump. 

Thank you for bringing this to attention!

**Comment by stoffeastrom** [comment]
Use the new `node-cli` package for AW 6
```sh
npm i -D @after-work.js/node-cli
```
https://aw.netlify.com/docs/installation.html#custom
