### ISSUE TITLE
Breaking changes v5 -> v6

### ISSUE THREAD

**Issue by peol** [qlik-oss/after-work.js#449]
We have a bunch of repos failing to bump to the new major: https://github.com/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+org%3Aqlik-oss+archived%3Afalse+sort%3Aupdated-desc+after-work.js

Any CHANGELOG/migration available somewhere?

**Comment by stoffeastrom** [comment]
Not yet, there was some late found issues that is being worked on. There shouldn't be any breaking changes more than under the hood though.

**Comment by peol** [comment]
I believe @axelssonHakan found some issues with glob patterns being different and/or underlying mocha requiring explicit timeout. Closing this as the issues we saw has been resolved.
